CREATE TABLE Class (
	`id` INT PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(50)
);

INSERT INTO Class (`name`) VALUES ("NITHIN"), ("SUMESH"), ("ROHIT"),("DEEPAK");


START TRANSACTION;

INSERT INTO Class (`name`) VALUES ("MOHIT");
ROLLBACK; 

INSERT INTO Class (`name`) VALUES ("MOHAN");
COMMIT;

START TRANSACTION;
SAVEPOINT Era;

INSERT INTO Class (`name`) VALUES ("NEWERA");
ROLLBACK TO Era;
SELECT * FROM Class;

COMMIT;
